import { Kubernetes } from "../src";

describe("Kubernetes", () => {
  test("has methods", async () => {
    const methods = Object.getOwnPropertyNames(Kubernetes.prototype);
    expect(methods.sort().join("\n")).toMatchInlineSnapshot(`
"constructor
createConfigMap
createCronJob
createDaemonSet
createDeployment
createHorizontalPodAutoscaler
createIngress
createJob
createNamespace
createPersistentVolumeClaim
createPod
createReplicaSet
createSecret
createService
deleteConfigMap
deleteCronJob
deleteDaemonSet
deleteDeployment
deleteHorizontalPodAutoscaler
deleteIngress
deleteJob
deleteNamespace
deletePersistentVolumeClaim
deletePod
deleteReplicaSet
deleteSecret
deleteService
exec
followLogs
getConfigMap
getCronJob
getDaemonSet
getDeployment
getHorizontalPodAutoscaler
getIngress
getJob
getLogs
getNamespace
getPersistentVolumeClaim
getPod
getReplicaSet
getSecret
getService
hasConfigMap
hasCronJob
hasDaemonSet
hasDeployment
hasHorizontalPodAutoscaler
hasIngress
hasJob
hasNamespace
hasPersistentVolumeClaim
hasPod
hasReplicaSet
hasSecret
hasService
listConfigMaps
listCronJobs
listDaemonSets
listDeployments
listHorizontalPodAutoscalers
listIngresses
listJobs
listNamespaces
listPersistentVolumeClaims
listPods
listReplicaSets
listSecrets
listServices
patchConfigMap
patchCronJob
patchDaemonSet
patchDeployment
patchHorizontalPodAutoscaler
patchIngress
patchJob
patchNamespace
patchPersistentVolumeClaim
patchPod
patchReplicaSet
patchSecret
patchService
replaceConfigMap
replaceCronJob
replaceDaemonSet
replaceDeployment
replaceHorizontalPodAutoscaler
replaceIngress
replaceJob
replaceNamespace
replacePersistentVolumeClaim
replacePod
replaceReplicaSet
replaceSecret
replaceService"
`);
  });
});
